/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.erthru.digitalpersonadb.ui.checkfinger;

import com.digitalpersona.onetouch.DPFPGlobal;
import com.digitalpersona.onetouch.DPFPSample;
import com.digitalpersona.onetouch.DPFPTemplate;
import com.erthru.digitalpersonadb.utils.DB;
import com.erthru.digitalpersonadb.utils.FingerPrintHelper;
import com.erthru.digitalpersonadb.utils.MsgBox;
import java.sql.ResultSet;
import javax.swing.SwingWorker;

/**
 *
 * @author supriantodjamalu
 */
public class CheckFingerInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form CheckFingerInternalFrame
     */
    public CheckFingerInternalFrame() {
        initComponents();
        
        auth();
        
    }

    private void auth(){
        
        class Task extends SwingWorker<String, Object>{

            @Override
            protected String doInBackground() throws Exception {
                
                DPFPSample sample = new FingerPrintHelper().getSample(null, null);
                Boolean success = false;
                
                ResultSet rs = DB.con().createStatement().executeQuery(""
                    + "SELECT tb_finger.*,"
                    + "tb_employee.* "
                    + ""
                    + "FROM tb_finger "
                    + ""
                    + "LEFT JOIN tb_employee ON tb_finger.employee_id = tb_employee.employee_id "
                    + "");
                
                while(rs.next()){
                    
                    byte[] b = null;
                    
                    b = new byte[rs.getString("finger_data").length() / 2];
                    
                    for(int i = 0; i < b.length; i++){
                        
                        int index = i * 2;
                        int v = Integer.parseInt(rs.getString("finger_data").substring(index, index + 2), 16);
                        b[i] = (byte) v;
                        
                    }
                    
                    DPFPTemplate temp2 = DPFPGlobal.getTemplateFactory().createTemplate();
                    temp2.deserialize(b);
                    
                    if(new FingerPrintHelper().verify(sample,temp2)){
                        MsgBox.success(rs.getString("employee_fullname"));
                        
                        success = true;
                        break;
                    }      
                    
                    
                }
                
                if(!success){
                    MsgBox.error("No data");
                }
                
                dispose();
                
                return null;
                
            }
            
        }
        
        new Task().execute();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBorder(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Put Your Finger In The Device");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
