/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.erthru.digitalpersonadb.ui.fingerdata;

import com.digitalpersona.onetouch.DPFPGlobal;
import com.digitalpersona.onetouch.DPFPTemplate;
import com.digitalpersona.onetouch.readers.DPFPReadersCollection;
import com.erthru.digitalpersonadb.utils.DB;
import com.erthru.digitalpersonadb.utils.FingerPrintHelper;
import com.erthru.digitalpersonadb.utils.MsgBox;
import javax.swing.SwingWorker;

/**
 *
 * @author supriantodjamalu
 */
public class FingerDataEnrollmentStartEnrollment extends javax.swing.JDialog {

    /**
     * Creates new form FingerDataEnrollmentStartEnrollment
     */
    public FingerDataEnrollmentStartEnrollment(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        DPFPReadersCollection readers = DPFPGlobal.getReadersFactory().getReaders();
        if (readers == null || readers.size() == 0) {
            MsgBox.error("Device not available");
            dispose();
        }
        
        enroll();
        
    }
    
    private void enroll(){
        
        class Task extends SwingWorker<String, Object>{

            @Override
            protected String doInBackground() throws Exception {
                
                DPFPTemplate temp = new FingerPrintHelper().getTemplate(null, 1);
                byte[] b = temp.serialize();
                         
                StringBuilder sb = new StringBuilder();
                
                for(byte b1 : b){
                    sb.append(String.format("%02X", b1));
                }
                
                String data = sb.toString();
                
                return data;
                
            }
            
            @Override
            public void done(){
                
                try{
                    
                    DB.con().createStatement().executeUpdate("INSERT INTO tb_finger(finger_data, employee_id) VALUES ('"+get()+"','"+FingerDataEnrollmentDialog.id+"')");
                    dispose();
                                        
                }catch(Exception e){
                    e.printStackTrace();
                }
                
            }
            
        }
        
        new Task().execute();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Put Your Finger In The Device");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FingerDataEnrollmentStartEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FingerDataEnrollmentStartEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FingerDataEnrollmentStartEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FingerDataEnrollmentStartEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FingerDataEnrollmentStartEnrollment dialog = new FingerDataEnrollmentStartEnrollment(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
