/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.erthru.digitalpersonadb.ui.fingerdata;

import com.erthru.digitalpersonadb.ui.employeedata.EmployeeDataUpdateDialog;
import com.erthru.digitalpersonadb.utils.DB;
import com.erthru.digitalpersonadb.utils.MsgBox;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author supriantodjamalu
 */
public class FingerDataEnrollmentSelectEmployeeDialog extends javax.swing.JDialog {

    /**
     * Creates new form FingerDataEnrollmentSelectEmployeeDialog
     */
    public FingerDataEnrollmentSelectEmployeeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        loadEmployeeTable();
        tableEmployee.requestFocus();
        
    }
    
    private void loadEmployeeTable(){
        
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("ID");
        dtm.addColumn("Full Name");
        dtm.addColumn("Email");
        
        try{
            
            ResultSet rs = DB.con().createStatement().executeQuery("SELECT * FROM tb_employee");
            
            while(rs.next()){
                
                dtm.addRow(new Object[]{
                
                    rs.getString("employee_id"),
                    rs.getString("employee_fullname"),
                    rs.getString("employee_email")
                
                });
                
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
        tableEmployee.setModel(dtm);
        
    }
    
    private void searchEmployeeTable(String keywords){
        
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("ID");
        dtm.addColumn("Full Name");
        dtm.addColumn("Email");
        
        try{
            
            ResultSet rs = DB.con().createStatement().executeQuery("SELECT * FROM tb_employee WHERE employee_id LIKE '%"+keywords+"%' OR employee_fullname LIKE '%"+keywords+"%'");
            
            while(rs.next()){
                
                dtm.addRow(new Object[]{
                
                    rs.getString("employee_id"),
                    rs.getString("employee_fullname"),
                    rs.getString("employee_email")
                
                });
                
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
        tableEmployee.setModel(dtm);
        
    }
    
    private Boolean isIdExist(String id){

        Boolean isExist = false;
        
        try{
            
            ResultSet rs = DB.con().createStatement().executeQuery("SELECT employee_id FROM tb_finger WHERE employee_id = '"+id+"'");
            if(rs.next())
                isExist = true;
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
        return isExist;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmployee = new javax.swing.JTable();
        txSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        tableEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEmployee);

        txSearch.setText("Search");
        txSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txSearchFocusLost(evt);
            }
        });
        txSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txSearchFocusGained
        if(txSearch.getText().equals("Search")){
            txSearch.setText("");
            txSearch.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txSearchFocusGained

    private void txSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txSearchFocusLost
        if(txSearch.getText().isEmpty()){
            txSearch.setText("Search");
            txSearch.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txSearchFocusLost

    private void tableEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEmployeeMouseClicked
        
        if(isIdExist(tableEmployee.getValueAt(tableEmployee.getSelectedRow(), 0).toString())){
            MsgBox.error("This Employee Already Enrollment.");
        }else{
            FingerDataEnrollmentDialog.id = tableEmployee.getValueAt(tableEmployee.getSelectedRow(), 0).toString();
            FingerDataEnrollmentDialog.fullName = tableEmployee.getValueAt(tableEmployee.getSelectedRow(), 1).toString();
            FingerDataEnrollmentDialog.email = tableEmployee.getValueAt(tableEmployee.getSelectedRow(), 2).toString();
            dispose();
        }
    }//GEN-LAST:event_tableEmployeeMouseClicked

    private void txSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSearchKeyReleased
        searchEmployeeTable(txSearch.getText());
    }//GEN-LAST:event_txSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FingerDataEnrollmentSelectEmployeeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FingerDataEnrollmentSelectEmployeeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FingerDataEnrollmentSelectEmployeeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FingerDataEnrollmentSelectEmployeeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FingerDataEnrollmentSelectEmployeeDialog dialog = new FingerDataEnrollmentSelectEmployeeDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEmployee;
    private javax.swing.JTextField txSearch;
    // End of variables declaration//GEN-END:variables
}
